local g = require('g')
local draw_canvas = require('draw/draw_canvas')
local draw_player = require('draw/draw_player')
local draw_map = require('draw/draw_map')
-- local draw_screen_center = require('draw/draw_screen_center')

function love.draw()
  love.graphics.setCanvas(g.canvas)
  love.graphics.clear()
  draw_map()
  draw_player()
  -- draw_screen_center()
  love.graphics.setBlendMode('alpha')
  love.graphics.setCanvas()
  love.graphics.clear(0, 0, 0)
  draw_canvas()
end
